# Generated by Django 6.0.2 on 2026-05-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='waiting', max_length=20)),
                ('estimated_time', models.IntegerField(help_text='زمان تخمینی به دقیقه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
            ],
        ),
    ]
