# Generated by Django 6.0.2 on 2026-05-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='custom_page_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='expires_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_profiles/'),
        ),
        migrations.AddField(
            model_name='business',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='searches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
