# Generated by Django 6.0.2 on 2026-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_custom_page_data_business_expires_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
