# Generated by Django 6.0.2 on 2026-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payment_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Authority پرداخت'),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه پرداخت'),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RefID پرداخت'),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=50, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='business',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت (ریال)'),
        ),
    ]
