# Generated by Django 6.0.2 on 2026-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_payment_authority_business_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='code_type',
            field=models.CharField(choices=[('normal', 'عادی'), ('special', 'ویژه')], default='normal', max_length=20),
        ),
    ]
