# Generated by Django 6.0.2 on 2026-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_code_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_type', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan', models.CharField(default='normal', max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('code_type', models.CharField(choices=[('normal', 'عادی'), ('special', 'ویژه')], default='normal', max_length=20)),
                ('business_code', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='pending_payment', max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ثبت موقت',
                'verbose_name_plural': 'ثبت\u200cهای موقت',
                'ordering': ['-created_at'],
            },
        ),
    ]
