# Generated by Django 6.0.2 on 2026-05-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_withdrawal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین برداشت'),
        ),
        migrations.AddField(
            model_name='business',
            name='total_withdrawn',
            field=models.IntegerField(default=0, verbose_name='مجموع برداشت\u200cها (ریال)'),
        ),
        migrations.AddField(
            model_name='business',
            name='wallet_balance',
            field=models.IntegerField(default=0, verbose_name='موجودی کیف پول (ریال)'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdrawal', 'برداشت'), ('payment', 'پرداخت'), ('reward', 'پاداش')], max_length=20)),
                ('amount', models.IntegerField(verbose_name='مبلغ (ریال)')),
                ('description', models.TextField(blank=True, null=True)),
                ('views_before', models.IntegerField(default=0, verbose_name='تعداد بازدید قبل از برداشت')),
                ('views_used', models.IntegerField(default=0, verbose_name='بازدیدهای استفاده شده')),
                ('views_remaining', models.IntegerField(default=0, verbose_name='بازدیدهای باقیمانده')),
                ('payment_for', models.CharField(blank=True, max_length=100, null=True, verbose_name='برای')),
                ('payment_details', models.JSONField(blank=True, null=True, verbose_name='جزئیات پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='businesses.business')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ درخواستی (ریال)')),
                ('method', models.CharField(choices=[('bank_transfer', 'حواله بانکی'), ('wallet', 'کیف پول درون\u200cبرنامه\u200cای')], default='wallet', max_length=20)),
                ('views_before', models.IntegerField(default=0, verbose_name='تعداد بازدید قبل از درخواست')),
                ('views_to_use', models.IntegerField(default=0, verbose_name='تعداد بازدید برای استفاده')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sheba_number', models.CharField(blank=True, max_length=26, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='businesses.business')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
                'ordering': ['-created_at'],
            },
        ),
    ]
