# Generated by Django 6.0.2 on 2026-05-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_business_last_withdrawal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BusinessLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_tracking', to='businesses.business')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'ip_hash'], name='businesses__busines_988ad4_idx'), models.Index(fields=['ip_hash'], name='businesses__ip_hash_28d619_idx')],
                'unique_together': {('business', 'ip_hash')},
            },
        ),
    ]
