# Generated by Django 6.0.2 on 2026-05-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('background', models.TextField()),
            ],
            options={
                'verbose_name': 'Bottom Ad',
                'verbose_name_plural': 'Bottom Ads',
            },
        ),
        migrations.CreateModel(
            name='Home1Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gradient', models.TextField()),
                ('features', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Home1 Ad',
                'verbose_name_plural': 'Home1 Ads',
            },
        ),
        migrations.CreateModel(
            name='Home2Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='ads/home2/')),
            ],
            options={
                'verbose_name': 'Home2 Ad',
                'verbose_name_plural': 'Home2 Ads',
            },
        ),
        migrations.CreateModel(
            name='HomeAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('background', models.TextField()),
            ],
            options={
                'verbose_name': 'Home Ad',
                'verbose_name_plural': 'Home Ads',
            },
        ),
        migrations.CreateModel(
            name='PopupAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('background', models.TextField()),
            ],
            options={
                'verbose_name': 'Popup Ad',
                'verbose_name_plural': 'Popup Ads',
            },
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
